- id: doi:10.3389/fevo.2022.1027399
  image: https://www.frontiersin.org/files/Articles/1027399/fevo-10-1027399-HTML/image_m/fevo-10-1027399-g002.jpg
  tags:
    - microbiome
    - ornithology
    - junco
