- id: doi:10.3389/fevo.2022.1027399
  image: https://www.frontiersin.org/files/Articles/1027399/fevo-10-1027399-HTML/image_m/fevo-10-1027399-g002.jpg
  tags:
    - microbiome
    - ornithology
    - junco

- id: doi:10.1128/MRA.00968-20
  image: images/fig1.jpeg
  tags:
    - microbiome
    - <i>Helianthus</i>

- id: doi:10.1128/mra.00982-22
  title: Draft Genome Sequence of a Multidrug-Resistant Strain of <i>Salmonella enterica</i>
    Serovar Typhimurium Isolated from a Pine Siskin (<i>Spinus pinus</i>)
  image: images/siskin.jpg
  tags:
    - whole genome sequencing
    - pine siskin
    - <i>Salmonella</i>
    
- id: doi:10.1093/jme/tjaa080
  title: <i>Rickettsia</i> spp. in Five Tick Species Collected in Central California
  image: images/phylogeny.jpeg
  tags:
    - vector-borne disease
    - tick
    - <i>Rickettsia</i>
    
- id: doi:10.1128/MRA.01367-18
  title: Transcriptome Sequence of Antibiotic-Treated <i>Pseudomonas aeruginosa</i>
  image: images/transcriptome.png
  tags: 
    - transcriptome
    - <i>Pseudomonas aeruginosa</i>
    - biofilm
    - antibiotic resistance

- id: doi:10.1093/jme/tjy213
  title: <i>Borrelia parkeri</i> in <i>Ornithodoros parkeri</i> (Ixodida: Argasidae)
    Collected Using Compact Dry Ice Traps in Madera County, California
  image: images/ticktrap.png
  tags:
    - <i>Borrelia parkeri</i>
    - <i>Ornithodoros parkeri</i>
    - tick
    - vector-borne disease
