- id: doi:10.3389/fevo.2022.1027399
  image: https://www.frontiersin.org/files/Articles/1027399/fevo-10-1027399-HTML/image_m/fevo-10-1027399-g002.jpg
  tags:
    - microbiome
    - ornithology
    - junco

- id: doi:10.1128/MRA.00968-20
  image: images/fig1.jpeg
  tags:
    - microbiome
    - <i>Helianthus</i>

- id: doi:10.1128/mra.00982-22
  title: Draft Genome Sequence of a Multidrug-Resistant Strain of <i>Salmonella enterica</i>
    Serovar Typhimurium Isolated from a Pine Siskin (<i>Spinus pinus</i>)
  image: images/siskin.jpg
  tags:
    - whole genome sequencing
    - pine siskin
    - <i>Salmonella</i>
    
- id: doi:10.1093/jme/tjaa080
  title: <i>Rickettsia</i> spp. in Five Tick Species Collected in Central California
  image: images/phylogeny.jpeg
  tags:
    - vector-borne disease
    - tick
    - <i>Rickettsia</i>
    
- id: doi:10.1128/MRA.01367-18
  title: Transcriptome Sequence of Antibiotic-Treated <i>Pseudomonas aeruginosa</i>
  image: images/transcriptome.png
  tags: 
    - transcriptome
    - <i>Pseudomonas aeruginosa</i>
    - biofilm
    - antibiotic resistance

- id: doi:10.1093/jme/tjy213
  title: '<i>Borrelia parkeri</i> in <i>Ornithodoros parkeri</i> (Ixodida: Argasidae)
    Collected Using Compact Dry Ice Traps in Madera County, California'
  image: images/ticktrap.png
  tags:
    - <i>Borrelia parkeri</i>
    - <i>Ornithodoros parkeri</i>
    - tick
    - vector-borne disease

- id: doi:10.1128/iai.00684-16
  title: Spermine and Spermidine Alter Gene Expression and Antigenic Profile of <i>Borrelia
    burgdorferi</i>
  image: images/pot.png
  tags:
    - <i>Borrelia burgdorferi</i>
    - vector-borne disease
    - Lyme disease

- id: doi:10.1002/mbo3.427
  image: images/mixedbiofilms.png
  tags:
    - <i>Pseudomonas aeruginosa</i>
    - <i>Staphylococcus aureus</i>
    - biofilm
    - transcriptome

- id: doi:10.1016/j.micinf.2016.03.004
  image: images/qpcr.jpg
  tags:
    - <i>Borrelia burgdorferi</i>
    - vector-borne disease
    - Lyme disease

- id: doi:10.1128/aac.04581-14
  title: Sublethal Concentrations of Carbapenems Alter Cell Morphology and Genomic
    Expression of <i>Klebsiella pneumoniae</i> Biofilms
  image: images/kpbiofilm.png
  tags:
    - <i>Klebsiella pneumoniae</i>
    - biofilm
    - transcriptome
    - antibiotic resistance

- id: doi:10.1128/iai.00521-13
  title: "MrkD\n            <sub>1P</sub>\n            from <i>Klebsiella pneumoniae</i>\
    \ Strain IA565 Allows for Coexistence with <i>Pseudomonas aeruginosa</i> and Protection\
    \ from Protease-Mediated Biofilm Detachment"
  image: images/ci.png
  tags: 
    - <i>Klebsiella pneumoniae</i>
    - biofilm
    - <i>Pseudomonas aeruginosa</i>

- id: doi:10.1128/genomea.01230-14
  title: Genome Sequence of a Multidrug-Resistant Strain of <i>Klebsiella pneumoniae</i>,
    BAMC 07-18, Isolated from a Combat Injury Wound
  tags: 
    - <i>Klebsiella pneumoniae</i>
    - antibiotic resistance
    - whole genome sequencing
