- id: doi:10.3389/fevo.2022.1027399
  image: https://www.frontiersin.org/files/Articles/1027399/fevo-10-1027399-HTML/image_m/fevo-10-1027399-g002.jpg
  tags:
    - microbiome
    - ornithology
    - junco

- id: doi:10.1128/MRA.00968-20
  image: images/fig1.jpeg
  tags:
    - microbiome
    - helianthus

- id: doi:10.1128/mra.00982-22
  title: Draft Genome Sequence of a Multidrug-Resistant Strain of <i>Salmonella enterica</i>
    Serovar Typhimurium Isolated from a Pine Siskin (<i>Spinus pinus</i>)
  image: images/siskin.jpg
  tags:
    - whole genome sequencing
    - pine siskin
    - salmonella
