- id: doi:10.3389/fevo.2022.1027399
  image: https://www.frontiersin.org/files/Articles/1027399/fevo-10-1027399-HTML/image_m/fevo-10-1027399-g002.jpg
  tags:
    - microbiome
    - ornithology
    - junco

- id:
  image: https://journals.asm.org/doi/10.1128/mra.00968-20#fig1
  tags:
    - microbiome
    - helianthus
